/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Summarization.java
 *
 * Created on Aug 31, 2013, 2:02:21 PM
 */
/**
 *
 * @author Trung
 */
public class SumUI extends javax.swing.JFrame {

    /**
     * Creates new form TestFrame
     */
    public SumUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbSrc1 = new javax.swing.JLabel();
        lbSum1 = new javax.swing.JLabel();
        btnSum = new javax.swing.JButton();
        sourePanel = new javax.swing.JScrollPane();
        txtSource = new javax.swing.JTextPane();
        sumPanel = new javax.swing.JScrollPane();
        txtSum = new javax.swing.JTextPane();
        txtSrcNWords = new javax.swing.JTextField();
        txtSumNWords = new javax.swing.JTextField();
        lbSrc2 = new javax.swing.JLabel();
        lbSum2 = new javax.swing.JLabel();
        lbNWords = new javax.swing.JLabel();
        lbTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tóm tắt văn bản");

        lbSrc1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSrc1.setText("Văn bản ban đầu");

        lbSum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSum1.setText("Văn bản tóm tắt");

        btnSum.setText("Tóm tắt");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        txtSource.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSource.setMinimumSize(new java.awt.Dimension(450, 550));
        txtSource.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSourceCaretUpdate(evt);
            }
        });
        sourePanel.setViewportView(txtSource);
        txtSource.getAccessibleContext().setAccessibleName("");

        txtSum.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSum.setMinimumSize(new java.awt.Dimension(450, 550));
        sumPanel.setViewportView(txtSum);

        txtSrcNWords.setEnabled(false);

        txtSumNWords.setText("100");

        lbSrc2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSrc2.setText("từ");

        lbSum2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSum2.setText("từ");

        lbNWords.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNWords.setText("Kết quả sau tóm tắt: ");

        lbTime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTime.setText("Thời gian chạy:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lbSrc1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSrcNWords, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbSrc2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSum)
                            .addComponent(sourePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbSum1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSumNWords, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSum2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(176, 176, 176))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lbNWords, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSrcNWords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbSrc1)
                        .addComponent(lbSum1)
                        .addComponent(txtSumNWords, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbSrc2)
                        .addComponent(lbSum2)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sourePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(sumPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSum)
                    .addComponent(lbTime)
                    .addComponent(lbNWords))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        if (txtSource.getText() != null) {
            txtSum.setText("");
//            btnSum.setText("...");
            int wordMax = Integer.parseInt(txtSumNWords.getText());
            long start = System.nanoTime();
            String out = Summarization.summarize(txtSource.getText(), wordMax);
            long end = System.nanoTime();
            txtSum.setText(out);
            lbTime.setText("Thời gian chạy: " + (end - start) / 1000000 + " ms");
            int nWords = out.split("\\s+").length;
//            btnSum.setText("Tóm tắt");
            lbNWords.setText("Kết quả sau tóm tắt: " + nWords + " từ");
        }
    }//GEN-LAST:event_btnSumActionPerformed

    private void txtSourceCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSourceCaretUpdate
        String s = txtSource.getText();
        int nWords = s.isEmpty() ? 0 : s.split("\\s+").length;
        txtSrcNWords.setText(nWords + "");
    }//GEN-LAST:event_txtSourceCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new SumUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSum;
    private javax.swing.JLabel lbNWords;
    private javax.swing.JLabel lbSrc1;
    private javax.swing.JLabel lbSrc2;
    private javax.swing.JLabel lbSum1;
    private javax.swing.JLabel lbSum2;
    private javax.swing.JLabel lbTime;
    private javax.swing.JScrollPane sourePanel;
    private javax.swing.JScrollPane sumPanel;
    private javax.swing.JTextPane txtSource;
    private javax.swing.JTextField txtSrcNWords;
    private javax.swing.JTextPane txtSum;
    private javax.swing.JTextField txtSumNWords;
    // End of variables declaration//GEN-END:variables
}
